default: &default
  adapter:  postgresql
  encoding: unicode
  host:     localhost
  pool:     5

development:
  <<: *default
  database: messenger_development

test:
  <<: *default
  database: messenger_test
